In [12]:
import pandas as pd
from functions import common_features_checker, feature_deletor

import warnings
warnings.filterwarnings('ignore')

In [3]:
app_train_poly = pd.read_csv('../data/cleanedData/cleaned_df.csv')
new_bureau_df = pd.read_csv('../data/cleanedData/new_bureau_df.csv')
payment_and_previous_df = pd.read_csv('../data/cleanedData/payment_and_previous_df.csv')
cash_balance_df = pd.read_csv('../data/cleanedData/cash_balance_df.csv')

**app_train_poly & cash_balance_df**

In [4]:
common_features_checker(app_train_poly, cash_balance_df)

['SK_ID_CURR']

In [7]:
app_train_poly = app_train_poly.merge(cash_balance_df, on='SK_ID_CURR')

**app_train_poly & new_bureau_df**

In [14]:
# check if there are common featues between the bureau and main datasets
common_features = common_features_checker(new_bureau_df, app_train_poly)
common_features

['SK_ID_CURR']

In [13]:
common_features.remove('SK_ID_CURR')
new_bureau_df = feature_deletor(new_bureau_df, common_features)

In [16]:
bureau_and_main_df = new_bureau_df.join(app_train_poly.set_index('SK_ID_CURR'), on='SK_ID_CURR', how='inner')

bureau_and_main_df

,SK_ID_CURR,DAYS_CREDIT,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,DAYS_CREDIT_UPDATE,STATUS,Months from today,...,1,EXT_SOURCE_2^2,EXT_SOURCE_2 EXT_SOURCE_3,EXT_SOURCE_2 DAYS_BIRTH,EXT_SOURCE_3^2,EXT_SOURCE_3 DAYS_BIRTH,DAYS_BIRTH^2,CNT_INSTALMENT,MONTHS_BALANCE,CNT_INSTALMENT_FUTURE
1,100002,2.875000,0.625000,-777.484287,108131.945625,82129.544982,7113.328115,2.125000,0.750000,28.250000,...,1.0,0.069142,0.036649,6.836663,0.019426,3.623770,676.0,24.0,-10.000000,15.000000
3,100010,6.000000,1.000000,-1077.718574,495000.000000,174003.750000,3114.757490,2.500000,0.000000,63.500000,...,1.0,0.510195,0.386178,37.142523,0.292307,28.114031,2704.0,10.0,-30.000000,5.000000
5,100019,2.000000,-14.500000,-1017.437148,360000.000000,122735.070000,135000.000000,1.000000,0.000000,16.000000,...,1.0,0.120155,0.235215,8.319216,0.460454,16.285625,576.0,12.0,-27.500000,7.875000
7,100032,3.250000,1.750000,-731.859287,317790.000000,0.000000,0.000000,1.750000,0.000000,34.750000,...,1.0,0.292815,0.356820,23.809443,0.434816,29.013843,1936.0,6.0,-46.000000,3.000000
8,100033,1.000000,-2.000000,-1017.437148,675000.000000,0.000000,0.000000,1.000000,0.000000,6.000000,...,1.0,0.469240,0.359286,19.180308,0.275097,14.685900,784.0,12.0,-22.000000,5.692308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134536,456244,5.260870,3.347826,-1400.032547,326478.934565,86195.502371,3002.578686,3.869565,0.217391,56.782609,...,1.0,0.623135,0.266555,44.205788,0.114023,18.909672,3136.0,9.0,-38.412500,11.575000
134537,456247,3.272727,-3.454545,-1066.573768,471405.681818,261710.509069,2831.597718,2.727273,0.000000,33.909091,...,1.0,0.251222,0.305382,16.540293,0.371217,20.106097,1089.0,12.0,-57.333333,4.518519
134539,456253,2.750000,-0.500000,-905.718574,990000.000000,448958.250000,0.000000,1.250000,0.000000,28.250000,...,1.0,0.286998,0.117248,21.964592,0.047899,8.973222,1681.0,6.0,-79.235294,2.000000
134540,456254,4.000000,3.000000,-859.000000,45000.000000,0.000000,6229.514980,2.000000,0.000000,36.000000,...,1.0,0.264363,0.339874,16.967373,0.436952,21.813777,1089.0,14.0,-5.550000,10.350000
134541,456255,3.454545,-8.363636,-990.653249,345629.045455,176924.397260,3397.917262,2.181818,0.000000,35.090909,...,1.0,0.502070,0.080722,33.302738,0.012978,5.354353,2209.0,36.0,-16.408451,15.140845

**bureau_and_main_df & payment_and_previous_df**

In [17]:
common_features = common_features_checker(bureau_and_main_df, payment_and_previous_df)
common_features

['SK_ID_CURR',
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
 'WEEKDAY_APPR_PROCESS_START_THURSDAY',
 'HOUR_APPR_PROCESS_START',
 'AMT_CREDIT',
 'AMT_GOODS_PRICE',
 'AMT_ANNUITY',
 'WEEKDAY_APPR_PROCESS_START_MONDAY',
 'WEEKDAY_APPR_PROCESS_START_TUESDAY',
 'MONTHS_BALANCE',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'WEEKDAY_APPR_PROCESS_START_SATURDAY',
 'WEEKDAY_APPR_PROCESS_START_SUNDAY']

In [18]:
common_features.remove('SK_ID_CURR')
payment_and_previous_df = feature_deletor(payment_and_previous_df, common_features)

In [19]:
main_bureau_payment_df = bureau_and_main_df.merge(payment_and_previous_df, on='SK_ID_CURR')

In [20]:
main_bureau_payment_df

,SK_ID_CURR,DAYS_CREDIT,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,DAYS_CREDIT_UPDATE,STATUS,Months from today,...,PRODUCT_COMBINATION_Cash X-Sell: low,PRODUCT_COMBINATION_Cash X-Sell: middle,PRODUCT_COMBINATION_POS household with interest,PRODUCT_COMBINATION_POS household without interest,PRODUCT_COMBINATION_POS industry with interest,PRODUCT_COMBINATION_POS industry without interest,PRODUCT_COMBINATION_POS mobile with interest,PRODUCT_COMBINATION_POS mobile without interest,PRODUCT_COMBINATION_POS other with interest,PRODUCT_COMBINATION_POS others without interest
0,100043,6.000000,4.500000,-1323.000000,166860.000000,0.000000,0.000000,4.000000,0.000000,62.000000,...,False,False,False,False,False,False,False,False,False,False
1,100048,1.000000,1.000000,-66.000000,22905.000000,0.000000,0.000000,1.000000,0.000000,2.000000,...,False,False,False,False,False,False,False,False,False,False
2,100100,5.600000,4.000000,-1101.000000,632748.690000,0.000000,3737.708988,2.200000,-0.400000,60.600000,...,False,False,False,False,False,False,False,False,False,False
3,100131,2.500000,-1.500000,-1017.437148,339750.000000,339131.250000,0.000000,1.000000,0.000000,22.000000,...,False,False,False,False,False,False,False,False,False,False
4,100139,2.500000,0.000000,-523.218574,189627.750000,167044.500000,0.000000,1.000000,0.000000,24.000000,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17897,456217,4.333333,1.833333,-1007.312383,329458.725000,106248.750000,2076.504993,2.000000,0.000000,45.000000,...,False,False,False,False,False,False,False,False,False,False
17898,456219,2.375000,0.875000,-801.788931,131342.670000,34271.279988,3114.757490,1.750000,0.000000,21.250000,...,False,False,False,False,False,False,False,False,False,False
17899,456233,1.000000,-1.000000,-1017.437148,282663.315000,223943.895000,0.000000,1.000000,0.000000,6.000000,...,False,False,False,False,False,False,False,False,False,False
17900,456242,2.000000,-1.000000,-1017.437148,198000.000000,186097.500000,0.000000,1.000000,0.000000,16.000000,...,False,False,False,False,False,False,False,False,False,False
17901,456244,5.260870,3.347826,-1400.032547,326478.934565,86195.502371,3002.578686,3.869565,0.217391,56.782609,...,False,False,False,False,False,False,False,False,False,False

**main_bureau_payment_df & cash_balance_df**

In [21]:
common_features = common_features_checker(main_bureau_payment_df, cash_balance_df)
common_features

['CNT_INSTALMENT', 'SK_ID_CURR', 'CNT_INSTALMENT_FUTURE', 'MONTHS_BALANCE']

In [22]:
common_features.remove('SK_ID_CURR')
main_bureau_payment_df = feature_deletor(main_bureau_payment_df, common_features)

In [23]:
all_df = main_bureau_payment_df.merge(cash_balance_df, on='SK_ID_CURR')

In [24]:
all_df

,SK_ID_CURR,DAYS_CREDIT,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,DAYS_CREDIT_UPDATE,STATUS,Months from today,...,PRODUCT_COMBINATION_POS household without interest,PRODUCT_COMBINATION_POS industry with interest,PRODUCT_COMBINATION_POS industry without interest,PRODUCT_COMBINATION_POS mobile with interest,PRODUCT_COMBINATION_POS mobile without interest,PRODUCT_COMBINATION_POS other with interest,PRODUCT_COMBINATION_POS others without interest,CNT_INSTALMENT,MONTHS_BALANCE,CNT_INSTALMENT_FUTURE
0,100043,6.000000,4.500000,-1323.000000,166860.000000,0.000000,0.000000,4.000000,0.000000,62.000000,...,False,False,False,False,False,False,False,60.0,-37.972973,34.324324
1,100048,1.000000,1.000000,-66.000000,22905.000000,0.000000,0.000000,1.000000,0.000000,2.000000,...,False,False,False,False,False,False,False,18.0,-8.125000,13.437500
2,100100,5.600000,4.000000,-1101.000000,632748.690000,0.000000,3737.708988,2.200000,-0.400000,60.600000,...,False,False,False,False,False,False,False,30.0,-24.274194,10.209677
3,100131,2.500000,-1.500000,-1017.437148,339750.000000,339131.250000,0.000000,1.000000,0.000000,22.000000,...,False,False,False,False,False,False,False,24.0,-37.500000,10.772727
4,100139,2.500000,0.000000,-523.218574,189627.750000,167044.500000,0.000000,1.000000,0.000000,24.000000,...,False,False,False,False,False,False,False,6.0,-39.457143,9.314286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17897,456217,4.333333,1.833333,-1007.312383,329458.725000,106248.750000,2076.504993,2.000000,0.000000,45.000000,...,False,False,False,False,False,False,False,24.0,-44.020979,15.076923
17898,456219,2.375000,0.875000,-801.788931,131342.670000,34271.279988,3114.757490,1.750000,0.000000,21.250000,...,False,False,False,False,False,False,False,10.0,-8.000000,5.860735
17899,456233,1.000000,-1.000000,-1017.437148,282663.315000,223943.895000,0.000000,1.000000,0.000000,6.000000,...,False,False,False,False,False,False,False,12.0,-5.500000,7.500000
17900,456242,2.000000,-1.000000,-1017.437148,198000.000000,186097.500000,0.000000,1.000000,0.000000,16.000000,...,False,False,False,False,False,False,False,10.0,-13.250000,5.718750
17901,456244,5.260870,3.347826,-1400.032547,326478.934565,86195.502371,3002.578686,3.869565,0.217391,56.782609,...,False,False,False,False,False,False,False,9.0,-38.412500,11.575000

In [25]:
all_df.TARGET.value_counts(normalize=True)

TARGET
0    0.895766
1    0.104234
Name: proportion, dtype: float64

In [26]:
app_train_poly.columns = app_train_poly.columns.str.replace('[^a-zA-Z0-9_]', '_')
all_df.columns = all_df.columns.str.replace('[^a-zA-Z0-9_]', '_')

In [27]:
path = '../data/cleanedData/'
all_df.to_csv(path + 'all_df.csv', index=False)